#! /bin/bash

PATH="../src/lib:$PATH" . parse-getopts.bash -h << ARG
  onoff -v verbose somewhat chatty
  value -t temp temporary file
  array -i item collected items
  required req1 first required argument
  required req2 second
  optional opt1 first optional argument
  optional opt2 second optional
  trailing rest everything else
ARG
